In [1]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing dataset

In [2]:
df = pd.read_csv('creditcard.csv')
X = df.iloc[: ,: -1].values
y = df.iloc[: , -1].values

In [31]:
X

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02, ...,
         1.33558377e-01, -2.10530535e-02,  1.49620000e+02],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
        -8.98309914e-03,  1.47241692e-02,  2.69000000e+00],
       [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
        -5.53527940e-02, -5.97518406e-02,  3.78660000e+02],
       ...,
       [ 1.72788000e+05,  1.91956501e+00, -3.01253846e-01, ...,
         4.45477214e-03, -2.65608286e-02,  6.78800000e+01],
       [ 1.72788000e+05, -2.40440050e-01,  5.30482513e-01, ...,
         1.08820735e-01,  1.04532821e-01,  1.00000000e+01],
       [ 1.72792000e+05, -5.33412522e-01, -1.89733337e-01, ...,
        -2.41530880e-03,  1.36489143e-02,  2.17000000e+02]])

In [32]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

Spliting the dataset into test and train

In [8]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X ,y , test_size = 0.25 , random_state =0)

Applying feature scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [34]:
X_train

array([[ 0.75665415,  1.04272047,  0.06657394, ..., -0.21031503,
        -0.2607924 , -0.35356699],
       [-0.2834455 ,  0.65277143,  0.27902921, ..., -0.02422764,
        -0.01672827, -0.34945825],
       [ 1.35155922, -0.21266203,  0.00863513, ...,  0.59177033,
         0.631378  , -0.33270102],
       ...,
       [-0.38298583,  0.77014889, -0.57187168, ..., -0.00246971,
         0.01108282, -0.21608519],
       [ 0.05149257,  0.91611288, -1.02491801, ..., -0.0825166 ,
        -0.100612  ,  0.33339889],
       [-0.41938711, -0.30165824,  0.45289483, ...,  0.21630833,
         0.36475181, -0.29225808]])

In [35]:
X_test

array([[ 0.65294852, -0.16231908,  0.64204284, ...,  0.26301127,
         0.46235694, -0.18685593],
       [ 1.31489192, -0.17584138,  0.56575459, ...,  0.18534466,
         0.50367918, -0.33557913],
       [ 1.21450679, -0.82415358, -1.47483831, ...,  0.69909712,
         1.2536383 ,  0.03219982],
       ...,
       [-0.78708496,  0.72254497, -0.27263126, ..., -0.02862602,
         0.01927491, -0.30420722],
       [ 1.22603296, -1.65266558,  1.28106533, ...,  1.15538662,
        -0.55092476,  0.04780754],
       [-1.14871584,  0.64789408, -0.44690401, ..., -0.25268833,
         0.03493675,  0.00872956]])

Building Model

In [19]:
from sklearn.linear_model import LogisticRegression
classifier =  LogisticRegression(random_state = 0)
classifier.fit(X_train , y_train)

C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

Predicting new results

In [22]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion matrix and accuracy score

In [24]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
accuracy_score(y_test , y_pred)

[[71071    11]
 [   40    80]]


0.999283727985169